/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) constr_par3_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

static const casadi_int casadi_s0[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s1[52] = {1, 36, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* constr_par3:(i0[18])->(o0[1x36,13nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][5] : 0;
  a3=sin(a2);
  a4=5.0000000000000000e-01;
  a5=1.2246467991473532e-16;
  a6=arg[0]? arg[0][7] : 0;
  a7=cos(a6);
  a8=(a5*a7);
  a9=-6.2000000000000000e-02;
  a10=(a9*a7);
  a11=(a8*a10);
  a12=7.5928101547135900e-18;
  a11=(a11+a12);
  a13=sin(a6);
  a14=(a5*a13);
  a15=(a9*a13);
  a16=(a14*a15);
  a11=(a11+a16);
  a11=(a4*a11);
  a16=arg[0]? arg[0][6] : 0;
  a17=sin(a16);
  a18=-1.9000000000000000e-01;
  a19=(a18*a17);
  a20=(a17*a19);
  a21=cos(a16);
  a22=(a18*a21);
  a23=(a21*a22);
  a20=(a20+a23);
  a23=1.9000000000000000e-01;
  a24=(a23*a21);
  a25=(a21*a24);
  a26=(a23*a17);
  a27=(a17*a26);
  a25=(a25+a27);
  a20=(a20-a25);
  a20=(a4*a20);
  a11=(a11-a20);
  a20=-1.2246467991473532e-16;
  a25=arg[0]? arg[0][9] : 0;
  a27=cos(a25);
  a28=arg[0]? arg[0][10] : 0;
  a29=sin(a28);
  a30=(a5*a29);
  a31=arg[0]? arg[0][11] : 0;
  a32=cos(a31);
  a33=arg[0]? arg[0][12] : 0;
  a34=cos(a33);
  a35=arg[0]? arg[0][13] : 0;
  a36=cos(a35);
  a37=-1.9500000000000001e-01;
  a38=arg[0]? arg[0][14] : 0;
  a39=cos(a38);
  a40=(a37*a39);
  a41=2.0899999999999999e-01;
  a42=-2.0899999999999999e-01;
  a43=(a42*a39);
  a44=(a39*a43);
  a45=sin(a38);
  a46=(a42*a45);
  a47=(a45*a46);
  a44=(a44+a47);
  a44=(a41-a44);
  a44=(a4*a44);
  a40=(a40-a44);
  a44=(a36*a40);
  a47=sin(a35);
  a48=(a5*a47);
  a49=(a9*a36);
  a50=(a48*a49);
  a51=(a5*a36);
  a52=(a9*a47);
  a53=(a51*a52);
  a50=(a50-a53);
  a50=(a4*a50);
  a44=(a44-a50);
  a50=(a37*a45);
  a53=(a39*a46);
  a54=(a45*a43);
  a53=(a53-a54);
  a53=(a4*a53);
  a50=(a50-a53);
  a53=(a47*a50);
  a44=(a44-a53);
  a53=(a34*a44);
  a54=-4.9000000000000002e-02;
  a55=sin(a33);
  a56=(a54*a55);
  a57=(a34*a56);
  a58=(a54*a34);
  a59=(a55*a58);
  a57=(a57-a59);
  a57=(a4*a57);
  a53=(a53-a57);
  a57=(a48*a40);
  a59=9.2985106525035170e-34;
  a60=(a9*a36);
  a61=(a36*a60);
  a61=(a59-a61);
  a62=(a9*a47);
  a63=(a47*a62);
  a61=(a61-a63);
  a63=(a47*a52);
  a64=(a36*a49);
  a63=(a63+a64);
  a61=(a61-a63);
  a61=(a4*a61);
  a57=(a57-a61);
  a61=(a51*a50);
  a57=(a57+a61);
  a61=(a55*a57);
  a53=(a53+a61);
  a61=(a32*a53);
  a63=(a42*a32);
  a64=(a32*a63);
  a65=sin(a31);
  a66=(a42*a65);
  a67=(a65*a66);
  a64=(a64+a67);
  a64=(a41-a64);
  a64=(a4*a64);
  a67=(a51*a60);
  a67=(a67+a12);
  a12=(a48*a62);
  a67=(a67+a12);
  a67=(a4*a67);
  a12=(a23*a55);
  a68=(a55*a12);
  a69=(a23*a34);
  a70=(a34*a69);
  a68=(a68+a70);
  a70=(a18*a34);
  a71=(a34*a70);
  a72=(a18*a55);
  a73=(a55*a72);
  a71=(a71+a73);
  a68=(a68-a71);
  a68=(a4*a68);
  a67=(a67-a68);
  a68=(a47*a40);
  a67=(a67-a68);
  a68=(a36*a50);
  a67=(a67-a68);
  a68=(a65*a67);
  a64=(a64+a68);
  a61=(a61-a64);
  a64=(a30*a61);
  a68=-9.2985106525035170e-34;
  a71=cos(a28);
  a73=6.2000000000000000e-02;
  a74=(a73*a71);
  a75=(a71*a74);
  a68=(a68-a75);
  a75=(a73*a29);
  a76=(a29*a75);
  a68=(a68-a76);
  a76=(a73*a29);
  a77=(a29*a76);
  a78=(a73*a71);
  a79=(a71*a78);
  a77=(a77+a79);
  a68=(a68-a77);
  a68=(a4*a68);
  a64=(a64-a68);
  a68=(a5*a71);
  a77=(a32*a67);
  a79=(a32*a66);
  a80=(a65*a63);
  a79=(a79-a80);
  a79=(a4*a79);
  a77=(a77-a79);
  a79=(a65*a53);
  a77=(a77+a79);
  a79=(a68*a77);
  a64=(a64+a79);
  a79=(a34*a57);
  a80=4.9000000000000002e-02;
  a81=(a55*a56);
  a82=(a34*a58);
  a81=(a81+a82);
  a81=(a80-a81);
  a81=(a4*a81);
  a82=(a55*a44);
  a81=(a81+a82);
  a79=(a79-a81);
  a64=(a64-a79);
  a81=(a27*a64);
  a82=sin(a25);
  a83=(a80*a82);
  a84=(a82*a83);
  a85=(a80*a27);
  a86=(a27*a85);
  a84=(a84+a86);
  a84=(a54-a84);
  a84=(a4*a84);
  a86=(a71*a61);
  a87=(a30*a78);
  a88=(a68*a76);
  a87=(a87-a88);
  a87=(a4*a87);
  a86=(a86-a87);
  a87=(a29*a77);
  a86=(a86-a87);
  a87=(a82*a86);
  a84=(a84+a87);
  a81=(a81-a84);
  a84=(a20*a81);
  a11=(a11+a84);
  a84=arg[0]? arg[0][8] : 0;
  a87=cos(a84);
  a88=(a27*a86);
  a89=(a27*a83);
  a90=(a82*a85);
  a89=(a89-a90);
  a89=(a4*a89);
  a88=(a88-a89);
  a89=(a82*a64);
  a88=(a88+a89);
  a89=(a87*a88);
  a90=(a42*a87);
  a91=(a87*a90);
  a92=sin(a84);
  a93=(a42*a92);
  a94=(a92*a93);
  a91=(a91+a94);
  a41=(a41-a91);
  a41=(a4*a41);
  a89=(a89-a41);
  a41=(a68*a74);
  a91=-7.5928101547135900e-18;
  a41=(a41+a91);
  a91=(a30*a75);
  a41=(a41+a91);
  a41=(a4*a41);
  a91=(a18*a82);
  a94=(a82*a91);
  a95=(a18*a27);
  a96=(a27*a95);
  a94=(a94+a96);
  a96=(a23*a27);
  a97=(a27*a96);
  a98=(a23*a82);
  a99=(a82*a98);
  a97=(a97+a99);
  a94=(a94-a97);
  a94=(a4*a94);
  a41=(a41-a94);
  a94=(a29*a61);
  a41=(a41-a94);
  a94=(a71*a77);
  a41=(a41-a94);
  a79=(a20*a79);
  a41=(a41+a79);
  a79=(a92*a41);
  a89=(a89-a79);
  a79=(a13*a89);
  a11=(a11-a79);
  a79=(a92*a88);
  a94=(a87*a93);
  a97=(a92*a90);
  a94=(a94-a97);
  a94=(a4*a94);
  a79=(a79-a94);
  a94=(a87*a41);
  a79=(a79+a94);
  a94=(a7*a79);
  a11=(a11-a94);
  a94=(a3*a11);
  a97=cos(a2);
  a99=(a14*a89);
  a100=(a7*a10);
  a59=(a59-a100);
  a100=(a13*a15);
  a59=(a59-a100);
  a100=(a9*a13);
  a101=(a13*a100);
  a102=(a9*a7);
  a103=(a7*a102);
  a101=(a101+a103);
  a59=(a59-a101);
  a59=(a4*a59);
  a59=(a59+a81);
  a99=(a99-a59);
  a59=(a8*a79);
  a99=(a99+a59);
  a59=(a21*a99);
  a81=(a54*a17);
  a101=(a17*a81);
  a103=(a54*a21);
  a104=(a21*a103);
  a101=(a101+a104);
  a101=(a80-a101);
  a101=(a4*a101);
  a104=(a7*a89);
  a105=(a14*a102);
  a106=(a8*a100);
  a105=(a105-a106);
  a105=(a4*a105);
  a104=(a104-a105);
  a105=(a13*a79);
  a104=(a104-a105);
  a105=(a17*a104);
  a101=(a101+a105);
  a59=(a59-a101);
  a101=(a97*a59);
  a94=(a94+a101);
  a1=(a1*a94);
  a94=sin(a0);
  a101=arg[0]? arg[0][4] : 0;
  a105=cos(a101);
  a106=(a21*a104);
  a107=(a21*a81);
  a108=(a17*a103);
  a107=(a107-a108);
  a107=(a4*a107);
  a106=(a106-a107);
  a107=(a17*a99);
  a106=(a106+a107);
  a107=(a105*a106);
  a108=sin(a101);
  a109=(a3*a59);
  a110=(a97*a11);
  a109=(a109-a110);
  a110=(a108*a109);
  a107=(a107+a110);
  a94=(a94*a107);
  a1=(a1-a94);
  if (res[0]!=0) res[0][1]=a1;
  a1=cos(a101);
  a94=cos(a0);
  a109=(a94*a109);
  a1=(a1*a109);
  a101=sin(a101);
  a106=(a94*a106);
  a101=(a101*a106);
  a1=(a1-a101);
  if (res[0]!=0) res[0][2]=a1;
  a1=cos(a2);
  a0=sin(a0);
  a101=(a0*a11);
  a108=(a94*a108);
  a106=(a108*a59);
  a101=(a101+a106);
  a1=(a1*a101);
  a2=sin(a2);
  a59=(a0*a59);
  a11=(a108*a11);
  a59=(a59-a11);
  a2=(a2*a59);
  a1=(a1-a2);
  if (res[0]!=0) res[0][3]=a1;
  a1=cos(a16);
  a94=(a94*a105);
  a105=(a4*a94);
  a2=(a103*a105);
  a59=(a108*a3);
  a11=(a0*a97);
  a59=(a59+a11);
  a11=(a4*a59);
  a101=(a81*a11);
  a2=(a2+a101);
  a101=(a17*a11);
  a106=(a21*a105);
  a101=(a101-a106);
  a101=(a54*a101);
  a2=(a2+a101);
  a0=(a0*a3);
  a108=(a108*a97);
  a0=(a0-a108);
  a108=(a4*a0);
  a26=(a26*a108);
  a2=(a2+a26);
  a26=(a17*a108);
  a26=(a23*a26);
  a2=(a2+a26);
  a19=(a19*a108);
  a2=(a2-a19);
  a19=(a17*a108);
  a19=(a18*a19);
  a2=(a2-a19);
  a19=(a59*a104);
  a2=(a2-a19);
  a19=(a94*a99);
  a2=(a2+a19);
  a1=(a1*a2);
  a16=sin(a16);
  a103=(a103*a11);
  a81=(a81*a105);
  a103=(a103-a81);
  a105=(a17*a105);
  a11=(a21*a11);
  a105=(a105+a11);
  a105=(a54*a105);
  a103=(a103+a105);
  a24=(a24*a108);
  a103=(a103+a24);
  a24=(a21*a108);
  a24=(a23*a24);
  a103=(a103+a24);
  a22=(a22*a108);
  a103=(a103-a22);
  a108=(a21*a108);
  a108=(a18*a108);
  a103=(a103-a108);
  a104=(a94*a104);
  a103=(a103+a104);
  a99=(a59*a99);
  a103=(a103+a99);
  a16=(a16*a103);
  a1=(a1-a16);
  if (res[0]!=0) res[0][4]=a1;
  a1=cos(a6);
  a16=(a59*a21);
  a103=(a94*a17);
  a16=(a16+a103);
  a103=(a4*a16);
  a99=(a100*a103);
  a94=(a94*a21);
  a59=(a59*a17);
  a94=(a94-a59);
  a59=(a4*a94);
  a17=(a8*a59);
  a21=(a13*a103);
  a17=(a17+a21);
  a17=(a9*a17);
  a99=(a99+a17);
  a17=(a15*a103);
  a99=(a99+a17);
  a17=(a13*a103);
  a21=(a4*a0);
  a104=(a14*a21);
  a17=(a17+a104);
  a17=(a9*a17);
  a99=(a99+a17);
  a17=(a0*a89);
  a99=(a99-a17);
  a15=(a15*a21);
  a17=(a102*a59);
  a15=(a15-a17);
  a17=(a16*a89);
  a15=(a15+a17);
  a15=(a5*a15);
  a99=(a99+a15);
  a15=(a94*a79);
  a99=(a99-a15);
  a1=(a1*a99);
  a6=sin(a6);
  a102=(a102*a103);
  a99=(a7*a103);
  a15=(a14*a59);
  a99=(a99-a15);
  a99=(a9*a99);
  a102=(a102+a99);
  a99=(a10*a103);
  a102=(a102+a99);
  a103=(a7*a103);
  a99=(a8*a21);
  a103=(a103+a99);
  a103=(a9*a103);
  a102=(a102+a103);
  a89=(a94*a89);
  a102=(a102+a89);
  a89=(a0*a79);
  a102=(a102-a89);
  a100=(a100*a59);
  a10=(a10*a21);
  a100=(a100+a10);
  a79=(a16*a79);
  a100=(a100+a79);
  a100=(a5*a100);
  a102=(a102+a100);
  a6=(a6*a102);
  a1=(a1-a6);
  if (res[0]!=0) res[0][5]=a1;
  a1=cos(a84);
  a14=(a16*a14);
  a6=(a0*a13);
  a14=(a14-a6);
  a6=(a94*a7);
  a14=(a14+a6);
  a6=(a4*a14);
  a102=(a93*a6);
  a8=(a16*a8);
  a7=(a0*a7);
  a8=(a8-a7);
  a94=(a94*a13);
  a8=(a8-a94);
  a94=(a4*a8);
  a13=(a90*a94);
  a102=(a102+a13);
  a13=(a92*a6);
  a7=(a87*a94);
  a13=(a13-a7);
  a13=(a42*a13);
  a102=(a102+a13);
  a13=(a8*a88);
  a102=(a102+a13);
  a13=(a14*a41);
  a102=(a102-a13);
  a1=(a1*a102);
  a84=sin(a84);
  a90=(a90*a6);
  a6=(a87*a6);
  a102=(a92*a94);
  a6=(a6+a102);
  a6=(a42*a6);
  a90=(a90+a6);
  a93=(a93*a94);
  a90=(a90-a93);
  a88=(a14*a88);
  a90=(a90+a88);
  a41=(a8*a41);
  a90=(a90+a41);
  a84=(a84*a90);
  a1=(a1-a84);
  if (res[0]!=0) res[0][6]=a1;
  a1=cos(a25);
  a84=(a8*a92);
  a90=(a14*a87);
  a84=(a84+a90);
  a90=(a4*a84);
  a41=(a85*a90);
  a0=(a20*a0);
  a0=(a0-a16);
  a16=(a4*a0);
  a88=(a83*a16);
  a41=(a41+a88);
  a88=(a82*a16);
  a93=(a27*a90);
  a88=(a88-a93);
  a88=(a80*a88);
  a41=(a41+a88);
  a8=(a8*a87);
  a14=(a14*a92);
  a8=(a8-a14);
  a14=(a4*a8);
  a98=(a98*a14);
  a41=(a41+a98);
  a98=(a82*a14);
  a98=(a23*a98);
  a41=(a41+a98);
  a91=(a91*a14);
  a41=(a41-a91);
  a91=(a82*a14);
  a91=(a18*a91);
  a41=(a41-a91);
  a91=(a0*a86);
  a41=(a41-a91);
  a91=(a84*a64);
  a41=(a41+a91);
  a1=(a1*a41);
  a25=sin(a25);
  a85=(a85*a16);
  a83=(a83*a90);
  a85=(a85-a83);
  a90=(a82*a90);
  a16=(a27*a16);
  a90=(a90+a16);
  a80=(a80*a90);
  a85=(a85+a80);
  a96=(a96*a14);
  a85=(a85+a96);
  a96=(a27*a14);
  a96=(a23*a96);
  a85=(a85+a96);
  a95=(a95*a14);
  a85=(a85-a95);
  a14=(a27*a14);
  a14=(a18*a14);
  a85=(a85-a14);
  a86=(a84*a86);
  a85=(a85+a86);
  a64=(a0*a64);
  a85=(a85+a64);
  a25=(a25*a85);
  a1=(a1-a25);
  if (res[0]!=0) res[0][7]=a1;
  a1=cos(a28);
  a25=(a0*a27);
  a85=(a84*a82);
  a25=(a25+a85);
  a85=(a4*a25);
  a64=(a76*a85);
  a84=(a84*a27);
  a0=(a0*a82);
  a84=(a84-a0);
  a0=(a4*a84);
  a82=(a68*a0);
  a27=(a29*a85);
  a82=(a82+a27);
  a82=(a73*a82);
  a64=(a64+a82);
  a82=(a75*a85);
  a64=(a64+a82);
  a82=(a29*a85);
  a27=(a4*a8);
  a86=(a30*a27);
  a82=(a82+a86);
  a82=(a73*a82);
  a64=(a64+a82);
  a82=(a8*a61);
  a64=(a64-a82);
  a75=(a75*a27);
  a82=(a78*a0);
  a75=(a75-a82);
  a82=(a25*a61);
  a75=(a75+a82);
  a75=(a5*a75);
  a64=(a64+a75);
  a75=(a84*a77);
  a64=(a64-a75);
  a1=(a1*a64);
  a28=sin(a28);
  a78=(a78*a85);
  a64=(a71*a85);
  a75=(a30*a0);
  a64=(a64-a75);
  a64=(a73*a64);
  a78=(a78+a64);
  a64=(a74*a85);
  a78=(a78+a64);
  a85=(a71*a85);
  a64=(a68*a27);
  a85=(a85+a64);
  a73=(a73*a85);
  a78=(a78+a73);
  a61=(a84*a61);
  a78=(a78+a61);
  a61=(a8*a77);
  a78=(a78-a61);
  a76=(a76*a0);
  a74=(a74*a27);
  a76=(a76+a74);
  a77=(a25*a77);
  a76=(a76+a77);
  a76=(a5*a76);
  a78=(a78+a76);
  a28=(a28*a78);
  a1=(a1-a28);
  if (res[0]!=0) res[0][8]=a1;
  a1=cos(a31);
  a30=(a25*a30);
  a28=(a8*a29);
  a30=(a30-a28);
  a28=(a84*a71);
  a30=(a30+a28);
  a28=(a4*a30);
  a78=(a66*a28);
  a68=(a25*a68);
  a71=(a8*a71);
  a68=(a68-a71);
  a84=(a84*a29);
  a68=(a68-a84);
  a84=(a4*a68);
  a29=(a63*a84);
  a78=(a78+a29);
  a29=(a65*a28);
  a71=(a32*a84);
  a29=(a29-a71);
  a29=(a42*a29);
  a78=(a78+a29);
  a29=(a30*a67);
  a78=(a78-a29);
  a29=(a68*a53);
  a78=(a78+a29);
  a1=(a1*a78);
  a31=sin(a31);
  a63=(a63*a28);
  a28=(a32*a28);
  a78=(a65*a84);
  a28=(a28+a78);
  a28=(a42*a28);
  a63=(a63+a28);
  a66=(a66*a84);
  a63=(a63-a66);
  a67=(a68*a67);
  a63=(a63+a67);
  a53=(a30*a53);
  a63=(a63+a53);
  a31=(a31*a63);
  a1=(a1-a31);
  if (res[0]!=0) res[0][9]=a1;
  a1=cos(a33);
  a31=(a68*a65);
  a63=(a30*a32);
  a31=(a31+a63);
  a63=(a4*a31);
  a53=(a58*a63);
  a20=(a20*a8);
  a20=(a20-a25);
  a25=(a4*a20);
  a8=(a56*a25);
  a53=(a53+a8);
  a8=(a55*a25);
  a67=(a34*a63);
  a8=(a8-a67);
  a8=(a54*a8);
  a53=(a53+a8);
  a68=(a68*a32);
  a30=(a30*a65);
  a68=(a68-a30);
  a30=(a4*a68);
  a72=(a72*a30);
  a53=(a53+a72);
  a72=(a55*a30);
  a72=(a18*a72);
  a53=(a53+a72);
  a12=(a12*a30);
  a53=(a53-a12);
  a12=(a55*a30);
  a12=(a23*a12);
  a53=(a53-a12);
  a12=(a20*a44);
  a53=(a53-a12);
  a12=(a31*a57);
  a53=(a53+a12);
  a1=(a1*a53);
  a33=sin(a33);
  a58=(a58*a25);
  a56=(a56*a63);
  a58=(a58-a56);
  a63=(a55*a63);
  a25=(a34*a25);
  a63=(a63+a25);
  a54=(a54*a63);
  a58=(a58+a54);
  a70=(a70*a30);
  a58=(a58+a70);
  a70=(a34*a30);
  a18=(a18*a70);
  a58=(a58+a18);
  a69=(a69*a30);
  a58=(a58-a69);
  a30=(a34*a30);
  a23=(a23*a30);
  a58=(a58-a23);
  a44=(a31*a44);
  a58=(a58+a44);
  a57=(a20*a57);
  a58=(a58+a57);
  a33=(a33*a58);
  a1=(a1-a33);
  if (res[0]!=0) res[0][10]=a1;
  a1=cos(a35);
  a33=(a20*a34);
  a58=(a31*a55);
  a33=(a33+a58);
  a58=(a4*a33);
  a57=(a52*a58);
  a31=(a31*a34);
  a20=(a20*a55);
  a31=(a31-a20);
  a20=(a4*a31);
  a55=(a51*a20);
  a34=(a47*a58);
  a55=(a55+a34);
  a55=(a9*a55);
  a57=(a57+a55);
  a55=(a62*a58);
  a57=(a57+a55);
  a55=(a47*a58);
  a34=(a4*a68);
  a44=(a48*a34);
  a55=(a55+a44);
  a55=(a9*a55);
  a57=(a57+a55);
  a55=(a68*a40);
  a57=(a57-a55);
  a62=(a62*a34);
  a55=(a49*a20);
  a62=(a62-a55);
  a55=(a33*a40);
  a62=(a62+a55);
  a62=(a5*a62);
  a57=(a57+a62);
  a62=(a31*a50);
  a57=(a57-a62);
  a1=(a1*a57);
  a35=sin(a35);
  a49=(a49*a58);
  a57=(a36*a58);
  a62=(a48*a20);
  a57=(a57-a62);
  a57=(a9*a57);
  a49=(a49+a57);
  a57=(a60*a58);
  a49=(a49+a57);
  a58=(a36*a58);
  a57=(a51*a34);
  a58=(a58+a57);
  a9=(a9*a58);
  a49=(a49+a9);
  a40=(a31*a40);
  a49=(a49+a40);
  a40=(a68*a50);
  a49=(a49-a40);
  a52=(a52*a20);
  a60=(a60*a34);
  a52=(a52+a60);
  a50=(a33*a50);
  a52=(a52+a50);
  a5=(a5*a52);
  a49=(a49+a5);
  a35=(a35*a49);
  a1=(a1-a35);
  if (res[0]!=0) res[0][11]=a1;
  a1=cos(a38);
  a48=(a33*a48);
  a35=(a68*a47);
  a48=(a48-a35);
  a35=(a31*a36);
  a48=(a48+a35);
  a35=(a4*a48);
  a49=(a46*a35);
  a33=(a33*a51);
  a68=(a68*a36);
  a33=(a33-a68);
  a31=(a31*a47);
  a33=(a33-a31);
  a4=(a4*a33);
  a31=(a43*a4);
  a49=(a49+a31);
  a31=(a45*a35);
  a47=(a39*a4);
  a31=(a31-a47);
  a31=(a42*a31);
  a49=(a49+a31);
  a33=(a37*a33);
  a49=(a49+a33);
  a1=(a1*a49);
  a38=sin(a38);
  a43=(a43*a35);
  a39=(a39*a35);
  a45=(a45*a4);
  a39=(a39+a45);
  a42=(a42*a39);
  a43=(a43+a42);
  a46=(a46*a4);
  a43=(a43-a46);
  a37=(a37*a48);
  a43=(a43+a37);
  a38=(a38*a43);
  a1=(a1-a38);
  if (res[0]!=0) res[0][12]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int constr_par3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int constr_par3_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int constr_par3_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void constr_par3_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int constr_par3_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void constr_par3_release(int mem) {
}

CASADI_SYMBOL_EXPORT void constr_par3_incref(void) {
}

CASADI_SYMBOL_EXPORT void constr_par3_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int constr_par3_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int constr_par3_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real constr_par3_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* constr_par3_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* constr_par3_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* constr_par3_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* constr_par3_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int constr_par3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_constr_par3(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[142];
  casadi_int *iw = 0;
  const casadi_real* arg[1] = {0};
  casadi_real* res[1] = {0};
  if (argc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"constr_par3\" failed. Too many input arguments (%d, max 1)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"constr_par3\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+31);
  --resc;
  res[0] = w+18;
  i = constr_par3(arg, res, iw, w+31, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"constr_par3\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s1, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[12];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_constr_par3(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "constr_par3")==0) {
    mex_constr_par3(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'constr_par3'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
