function [J,Jd] = Link1Jacobian(in1,in2)
%LINK1JACOBIAN
%    [J,JD] = LINK1JACOBIAN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    29-Nov-2020 17:42:37

p1_1 = in2(1);
p2_1 = in2(2);
q3 = in1(3,:);
qd3 = in1(10,:);
t2 = conj(p1_1);
t3 = cos(q3);
t4 = conj(p2_1);
t5 = sin(q3);
t6 = t3.*t4;
t7 = t6-t2.*t5;
J = reshape([1.0,0.0,0.0,1.0,t7,-t2.*t3-t4.*t5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,7]);
if nargout > 1
    Jd = reshape([0.0,0.0,0.0,0.0,-qd3.*(t2.*t3+t4.*t5),-qd3.*t7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,7]);
end
