function [J,Jd] = Link3Jacobian(in1,in2)
%LINK3JACOBIAN
%    [J,JD] = LINK3JACOBIAN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    29-Nov-2020 17:42:44

p1_1 = in2(1);
p2_1 = in2(2);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
qd3 = in1(10,:);
qd4 = in1(11,:);
qd5 = in1(12,:);
t2 = sin(q3);
t3 = cos(q3);
t4 = sin(q4);
t5 = cos(q4);
t6 = cos(q5);
t7 = t2.*t4;
t15 = t3.*t5;
t8 = t7-t15;
t9 = sin(q5);
t10 = t3.*t4;
t11 = t2.*t5;
t12 = t10+t11;
t13 = t2.*t4.*(2.09e2./1.0e3);
t14 = conj(p1_1);
t16 = t8.*t9;
t22 = t6.*t12;
t27 = t16-t22;
t17 = t14.*t27;
t18 = conj(p2_1);
t19 = t6.*t8;
t20 = t9.*t12;
t21 = t19+t20;
t23 = t3.*t4.*(2.09e2./1.0e3);
t24 = t2.*t5.*(2.09e2./1.0e3);
t25 = t14.*(t19+t20);
t26 = t18.*(t16-t22);
t28 = t23+t24+t25+t26;
t29 = t14.*t21;
t30 = t18.*t27;
t31 = qd5.*(t29+t30);
t32 = qd4.*t28;
t34 = t18.*t21;
t33 = t17-t34;
J = reshape([1.0,0.0,0.0,1.0,t2.*(-1.9e1./1.0e2)+t13+t17-t3.*t5.*(2.09e2./1.0e3)-t18.*t21,t3.*(-1.9e1./1.0e2)+t23+t24+t25+t26,t13+t17-t3.*t5.*(2.09e2./1.0e3)-t18.*t21,t28,t33,t25+t26,0.0,0.0,0.0,0.0],[2,7]);
if nargout > 1
    t35 = t18.*(t19+t20);
    t36 = t3.*t5.*(2.09e2./1.0e3);
    t37 = t13+t17-t35-t36;
    t38 = t17-t35;
    Jd = reshape([0.0,0.0,0.0,0.0,t31+t32+qd3.*(t3.*(-1.9e1./1.0e2)+t23+t24+t29+t30),-qd4.*(t13+t17-t34-t3.*t5.*(2.09e2./1.0e3))-qd5.*t33+qd3.*(t2.*(1.9e1./1.0e2)-t13-t17+t35+t36),t31+t32+qd3.*t28,-qd3.*t37-qd4.*t37-qd5.*t38,t31+qd3.*(t29+t30)+qd4.*(t29+t30),-qd3.*t38-qd4.*t38-qd5.*t38,0.0,0.0,0.0,0.0],[2,7]);
end
