function [J,Jd] = Link4Jacobian(in1,in2)
%LINK4JACOBIAN
%    [J,JD] = LINK4JACOBIAN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    29-Nov-2020 17:42:50

p1_1 = in2(1);
p2_1 = in2(2);
q3 = in1(3,:);
q6 = in1(6,:);
qd3 = in1(10,:);
qd6 = in1(13,:);
t2 = sin(q3);
t3 = cos(q3);
t4 = cos(q6);
t5 = sin(q6);
t6 = conj(p1_1);
t7 = t3.*t5;
t8 = t2.*t4;
t9 = t7+t8;
t10 = conj(p2_1);
t11 = t2.*t5;
t13 = t3.*t4;
t12 = t11-t13;
t14 = t6.*(t11-t13);
t15 = t3.*(1.9e1./1.0e2);
t16 = t6.*t12;
t17 = qd6.*(t16-t9.*t10);
t18 = t2.*(1.9e1./1.0e2);
J = reshape([1.0,0.0,0.0,1.0,t18-t6.*t9-t10.*t12,t14+t15-t9.*t10,0.0,0.0,0.0,0.0,-t6.*t9-t10.*t12,t14-t9.*t10,0.0,0.0],[2,7]);
if nargout > 1
    t19 = t6.*t9;
    t20 = t10.*(t11-t13);
    t21 = t19+t20;
    t22 = qd6.*t21;
    Jd = reshape([0.0,0.0,0.0,0.0,t17+qd3.*(t15+t16-t9.*t10),t22+qd3.*(-t18+t19+t10.*t12),0.0,0.0,0.0,0.0,t17+qd3.*(t16-t9.*t10),t22+qd3.*t21,0.0,0.0],[2,7]);
end
